<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="Dalamud.Plugin.Bootstrap.targets" />

	<PropertyGroup>
		<Authors>Aulus mal Asina</Authors>
		<Company></Company>
		<Version>0.0.1.0</Version>
		<Description>Resonant</Description>
		<Copyright></Copyright>
		<PackageProjectUrl></PackageProjectUrl>
		<OutputPath>$(AppData)\XIVLauncher\devPlugins\Resonant\</OutputPath>
		<TargetFramework>net8.0-windows8.0</TargetFramework>
	</PropertyGroup>
</Project>
